import Head from 'next/head';
import WriteForm from '@/components/write/WriteForm';
import FullHeightPage from '@/components/system/FullHeightPage';
import { useRouter } from 'next/router';
import { useQuery } from '@tanstack/react-query';
import { Post } from '@/lib/api/types';
import { getPostByTitle } from '@/lib/api/post';
import { GetServerSideProps } from 'next';
import { dehydrate, QueryClient } from '@tanstack/query-core';

function UpdatePage() {
  const { query } = useRouter();
  const { data: post } = useQuery<Post>({
    queryKey: ['posts', query.category, query.post_title],
    queryFn: () => getPostByTitle(query.post_title as string),
    refetchOnWindowFocus: false,
    enabled: !!query.post_title,
  });
  return (
    <>
      <Head>
        <title>(작성중){post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FullHeightPage>
        <WriteForm post={post} />
      </FullHeightPage>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const {
    req,
    query: { category, post_title },
  } = context;

  const queryKey = ['posts', category, post_title];

  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(queryKey, () =>
    getPostByTitle(post_title as string),
  );

  if (!queryClient.getQueryData(queryKey)) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  };
};

export default UpdatePage;
