import Head from 'next/head';
import WriteForm from '@/components/write/WriteForm';
import { GetServerSideProps } from 'next';

function WritePage() {
  return (
    <>
      <Head>
        <title>새 글 글작성 | mucbog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WriteForm />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const { cookies } = req;
  if (!cookies.access_token) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
      props: {},
    };
  }
  return {
    props: {},
  };
};

export default WritePage;
