import Head from 'next/head';
import BasicTemplate from '@/components/templates/BasicTemplate';
import useMyAccount from '@/lib/hooks/useMyAccount';
import { GetServerSideProps } from 'next';
import { dehydrate, isServer, QueryClient } from '@tanstack/query-core';
import { getMyAccount } from '@/lib/api/auth';
import axios from 'axios';
import styled from "@emotion/styled";
import {media} from "@/lib/media";

export default function Home() {
  const { data: userData } = useMyAccount();

  return (
    <>
      <Head>
        <title>mucbog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate>
        <Content>
          {userData?.username}님 어서와요
        </Content>
      </BasicTemplate>
    </>
  );
}

const Content = styled.div`
  padding: 16px;
  ${media.wide} {
    width: 1280px;
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
  }
`;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req } = ctx;
  const cookie = req ? req.headers.cookie : '';
  if (req && cookie) {
    axios.defaults.headers.Cookie = cookie;
  }

  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(['me'], getMyAccount);

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  };
};
