import Head from 'next/head';
import BasicTemplate from '@/components/templates/BasicTemplate';
import AuthForm from '@/components/auth/AuthForm';
import { GetServerSideProps } from 'next';

function AuthPage() {
  return (
    <>
      <Head>
        <title>로그인 | mucbog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate desktopHeaderVisible={false}>
        <AuthForm />
      </BasicTemplate>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const { cookies } = req;
  if (cookies.access_token) {
    return {
      redirect: {
        permanent: false,
        destination: '/',
      },
      props: {},
    };
  }
  return {
    props: {},
  };
};

export default AuthPage;
